### ISSUE TITLE
startScreenCapture 录制屏幕指定区域bug

### ISSUE THREAD

**Issue by xiechao-gd** [AgoraIO-Community/Agora-RTC-SDK-for-Electron#15]
使用 startScreenCapture 方法录制屏幕指定区域没有效果，rect赋值{x: 200, y: 200, width: 200, height: 200}根本不起作用

**Comment by Tomyail** [comment]
用{ left,right,top,bottom} 来计算,相对于全局屏幕坐标

**Comment by xiechao-gd** [comment]
用{ left,right,top,bottom} 试过了也不行，都是分享的整个屏幕，并且我电脑是双屏显示的时候，分享的是A屏幕右边 + B屏幕左边的区域
![1533806639 1](https://user-images.githubusercontent.com/10398466/43890649-dbe15770-9bf9-11e8-8a78-94f9cacb3b1f.jpg)

**Comment by xiechao-gd** [comment]
声网的 web sdk 支持 canvas 推流吗？

**Comment by menthays** [comment]
left right top bottom 都是相对于左上角的（也就是说左上角那个点是0，0），因此请务必检查参数是否合法（right 一定大于 left， bottom 一定大于 top）。

至于canvas推流，您指的是裸数据推流么？目前暂时还不支持:disappointed_relieved:

**Comment by xiechao-gd** [comment]
谢谢，我已经通过修改压缩过的AgoraRTCSDK-2.3.1.js源码，来达到进行canvas裸数据推流的效果了。
![1534158538 1](https://user-images.githubusercontent.com/10398466/44028561-d4a0f03e-9f2c-11e8-99ec-cac7a28ccb79.jpg)

**Comment by sophiaWang611** [comment]
> 用{ left,right,top,bottom} 试过了也不行，都是分享的整个屏幕，并且我电脑是双屏显示的时候，分享的是A屏幕右边 + B屏幕左边的区域
> ![1533806639 1](https://user-images.githubusercontent.com/10398466/43890649-dbe15770-9bf9-11e8-8a78-94f9cacb3b1f.jpg)

请问这个问题后来是怎么解决的，我遇到了相同的问题，指定{ left,right,top,bottom}仍旧会出现两个屏幕各共享一半的情况。

**Comment by plutoless** [comment]
这边给的left, right, top, bottom分别是什么值？
