### ISSUE TITLE
Recording volume reduced automaticly

### ISSUE THREAD

**Issue by panxiuqing** [AgoraIO-Community/Agora-RTC-SDK-for-Electron#4]
麦克风设备的音量会自动减小：

audiodevicevolumechanged 1 255 0 // ********* 我设置的音量 ***************** 
client.js:18 apicallexecuted rtc.api.enable_lastmile_test 0 
client.js:18 apicallexecuted rtc.lastmile_test 0 
client.js:18 apicallexecuted che.audio.volume_indication 0 
client.js:18 apicallexecuted rtc.api.join_channel 0 
client.js:18 audiodevicevolumechanged 1 240 0 // ********* 音量自动变小 ***************** client.js:18 audiovolumeindication 0 281 1 25 
client.js:7 audiovolumeindication 0 281 1 25 
client.js:18 networkquality 0 1 1 
client.js:18 audiovolumeindication 0 25 1 25 
client.js:7 audiovolumeindication 0 25 1 25 
client.js:18 audiovolumeindication 0 25 1 25 
client.js:7 audiovolumeindication 0 25 1 25 
client.js:18 networkquality 0 1 1 
client.js:18 audiovolumeindication 1 279 1 23 
client.js:7 audiovolumeindication 1 279 1 23 
client.js:2 时间同步完成，时差3568毫秒 
client.js:18 audiovolumeindication 0 25 1 25 
client.js:7 audiovolumeindication 0 25 1 25 
client.js:18 networkquality 0 1 1 
client.js:18 audiovolumeindication 0 25 1 25 
client.js:7 audiovolumeindication 0 25 1 25 
client.js:18 audiovolumeindication 1 281 1 25 
client.js:7 audiovolumeindication 1 281 1 25 
client.js:18 networkquality 0 1 1 
client.js:18 audiovolumeindication 0 25 1 25 
client.js:7 audiovolumeindication 0 25 1 25 
client.js:18 audiovolumeindication 1 281 1 25 
client.js:7 audiovolumeindication 1 281 1 25 
client.js:18 networkquality 0 1 1 
client.js:18 audiovolumeindication 0 25 1 25 
client.js:7 audiovolumeindication 0 25 1 25 
client.js:18 audiovolumeindication 1 281 1 25 
client.js:7 audiovolumeindication 1 281 1 25 
client.js:18 networkquality 0 1 1 
client.js:18 audiovolumeindication 1 270 1 14 
client.js:7 audiovolumeindication 1 270 1 14 
client.js:18 audiovolumeindication 0 25 1 25 
client.js:7 audiovolumeindication 0 25 1 25 
client.js:18 networkquality 0 1 1 
client.js:18 audiovolumeindication 0 25 1 25 
client.js:7 audiovolumeindication 0 25 1 25 
client.js:18 audiovolumeindication 1 256 1 0 
client.js:7 audiovolumeindication 1 256 1 0 
client.js:18 networkquality 0 1 1 
client.js:18 audiodevicevolumechanged 1 186 0 // ********* 音量自动变小 ***************** 
client.js:18 audiovolumeindication 1 256 1 0 
client.js:7 audiovolumeindication 1 256 1 0 
client.js:18 audiodevicevolumechanged 1 133 0 // ********* 音量自动变小 ***************** 
client.js:18 audiovolumeindication 1 256 1 0 
client.js:7 audiovolumeindication 1 256 1 0 
client.js:18 networkquality 0 1 1 
client.js:18 audiovolumeindication 0 256 1 0 
client.js:7 audiovolumeindication 0 256 1 0

**Comment by plutoless** [comment]
@panxiuqing 这是sdk的行为，在麦克风发生爆音的时候会自动降低音量，如果需要手动关闭这个功能可以查看我们的release/2.0.7分支，使用私有接口可以关闭该行为，详情可以询问客户支持
这个问题和electron sdk本身无关所以关闭了，有需要的话请重新打开
