### ISSUE TITLE
我在打开应用的时候遇到这样的错误

### ISSUE THREAD

**Issue by Mrxdh** [AgoraIO-Community/Agora-RTC-SDK-for-Electron#9]
我在打包成mac包以后，
把这个包给别人，别人打开应用报了一个image not found，我不知道为什么

bundle.js:1 Uncaught Error: Cannot open /Developer/git/kuban-desktop/node_modules/_agora-electron-sdk@2.2.1-beta@agora-electron-sdk/build/Release/agora_node_ext.node: Error: dlopen(/Developer/git/kuban-desktop/node_modules/_agora-electron-sdk@2.2.1-beta@agora-electron-sdk/build/Release/agora_node_ext.node, 1): image not found
    at Object.<anonymous> (bundle.js:1)
    at Object../node_modules/_agora-electron-sdk@2.2.1-beta@agora-electron-sdk/build/Release/agora_node_ext.node (bundle.js:1)
    at n (bundle.js:1)
    at Object../node_modules/_agora-electron-sdk@2.2.1-beta@agora-electron-sdk/js/AgoraSdk.js (bundle.js:1)
    at n (bundle.js:1)
    at Object../components/Projector.js (bundle.js:1)
    at n (bundle.js:1)
    at Object../containers/HomeBox.js (bundle.js:1)
    at n (bundle.js:1)
    at Object../routes.js (bundle.js:65)
    at n (bundle.js:1)
    at Object../containers/Root.js (bundle.js:1)
    at n (bundle.js:1)
    at Object../index.js (bundle.js:1)
    at n (bundle.js:1)
    at Object.11 (bundle.js:65)
bundle.js:1 [19:47:59.261] command execution success

**Comment by menthays** [comment]
请提供以下信息：
1. 打包的方式
2. “别人”的操作系统也是mac么
3. 检查该路径下是否有必须的.node文件
4. 引用sdk的方式

**Comment by Mrxdh** [comment]
1. 我们项目用的模版是electron-react-boilerplate，其中打包方式 npm run package，我们项目版本可能比较老一点
2. 别人的操作系统也是mac
3. 该项目路径下存在agora_node_ext.node文件。
4. 我采用了2种方式引用  第一种方式就是官方示例的方式 npm install agora-electron-sdk 然后 import AgoraRtcEngine from 'agora-electron-sdk’; 第二种方式 直接吧npm包文件移到项目中直接引用，但是报的错误信息都是一样的 
![Alt text](https://media-ssl.kuban.io/static/file/2/WechatIMG765.jpeg "错误图片")

**Comment by menthays** [comment]
这个问题看起来是因为.node文件存在于开发目录下，然而却不在打包后的结果中。.node文件相当于是dll文件，您需要将他置于打包结果始终能访问到的位置。

1. 如下图在package.json build字段 file 属性中增加sdk所在的目录，然后通过相对路径访问它（下图中的AgoraSdk）。
![package json](https://user-images.githubusercontent.com/20641719/42427572-d2a25ff2-8361-11e8-9680-85285ecb244d.png)
2. 使用合适的 webpack loader 将node_modules中的sdk移动到打包结果中，类似file-loader的做法

Electron+.node+webpack项目由于自身的原因，项目结构和配置会比较复杂，我们目前也在寻求更好的方案，如有您有什么改进的建议，可以联系我们或者提交pr

**Comment by sweetylulu** [comment]
问题解决了吗

**Comment by zhangtao1104** [comment]
你这边有相同的问题？

是不是 dev 模式正常，打包运行异常?

**Comment by sweetylulu** [comment]
> 你这边有相同的问题？
> 
> 是不是 dev 模式正常，打包运行异常?

dev的时候控制台就报这个错

**Comment by sweetylulu** [comment]
> 你这边有相同的问题？
> 
> 是不是 dev 模式正常，打包运行异常?

页面引入import AgoraRtcEngine from "agora-electron-sdk";报错

**Comment by sweetylulu** [comment]
> 这个问题看起来是因为.node文件存在于开发目录下，然而却不在打包后的结果中。.node文件相当于是dll文件，您需要将他置于打包结果始终能访问到的位置。
> 
> 1. 如下图在package.json build字段 file 属性中增加sdk所在的目录，然后通过相对路径访问它（下图中的AgoraSdk）。
>    ![package json](https://user-images.githubusercontent.com/20641719/42427572-d2a25ff2-8361-11e8-9680-85285ecb244d.png)
> 2. 使用合适的 webpack loader 将node_modules中的sdk移动到打包结果中，类似file-loader的做法
> 
> Electron+.node+webpack项目由于自身的原因，项目结构和配置会比较复杂，我们目前也在寻求更好的方案，如有您有什么改进的建议，可以联系我们或者提交pr

问题解决了吗

**Comment by sweetylulu** [comment]
> * 我们项目用的模版是electron-react-boilerplate，其中打包方式 npm run package，我们项目版本可能比较老一点
> * 别人的操作系统也是mac
> * 该项目路径下存在agora_node_ext.node文件。
> * 我采用了2种方式引用  第一种方式就是官方示例的方式 npm install agora-electron-sdk 然后 import AgoraRtcEngine from 'agora-electron-sdk’; 第二种方式 直接吧npm包文件移到项目中直接引用，但是报的错误信息都是一样的
>   下图用的是第二种方式
>   ![Alt text](https://camo.githubusercontent.com/867a4fbb8c4c71f419a83be7ff07120f948d1b3def557e8f283f33d878d02c73/68747470733a2f2f6d656469612d73736c2e6b7562616e2e696f2f7374617469632f66696c652f322f576563686174494d473736352e6a706567)

问题解决了吗
